# -*- coding: utf-8 -*-
"""GPU

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dDwjqjsIG0h9NUiXdmlEUZoF1e_JmFxK
"""

#Tenemos:GPU

#CPU: Pocos nucleos e idal para temas secuenciales

#GPU:Muchos nucleos e ideal para realizar la operación sobre muchas datos
#Vectores/matrices, deep learning, imagenes, videos, algebra lineal masiva

#Para usar GPU normalmente lo que se hace:
# a) Datos sobre RAM (CPU)
# b) Mandar a VRAM (GPU)
# c) Calculos
# d) Regresar resultados a RAM

# El proceso anterior (ir y volver) puede ser caro, por eso en tareas pequeñas la GPU puede ser lenta
# Sin embargo, las tareas, el tareas grandes la GPU gana

!nvidia-smi

# Lo anterior significa que:
# GPU: Tesla T4
# GPU util: 0% es decir, ahorita no se esta usando
# Memory usage: 0 MiB aun no se ha mandado nada a la GPU
#CUDA versión reportada 13.0

#Tarea:Modelos de tarjeta Graficas / procesadores (explicar)

import time
import torch

N = 20_000_000 #Creamos vectores de 20_000_000

#Generamos un tensor de namaño N, con numeros aleatorios, el cual se crea en CPU (RAM), son vectores de varias dimenciones
x_cpu = torch.rand(N) #generamos 2 vectores
y_cpu = torch.rand(N)

# Porcedemos a cuantificar la suma de dichos vectores
t0 = time.perf_counter()
z_cpu = x_cpu + y_cpu
t1 = time.perf_counter()
print("Suma en CPU: ", round(t1 - t0, 4),"s")

#GPU
if torch.cuda.is_available(): #¿Hay GPU disponible?
  x_gpu = x_cpu.to("cuda") #Copiar los tensores desde CPU (RAM) hacia GPU (VRAM)
  y_gpu = y_cpu.to("cuda")
  #Lo anterior implica que ahora las operaciones viviran en GPU
  _ = x_gpu + y_gpu # La primera operacion realizara en GPU puede ser lenta
  #Por inicializaciones internas y por lo tanto, al colocarle "_" indicamos que
  #nos interesa guardar el primer resultado
  torch.cuda.synchronize() #Espera a que la GPU termine para medir el tiempo

  t0 = time.perf_counter()
  z_cpu = x_cpu + y_cpu
  t1 = time.perf_counter()
  print("Suma en CPU: ", round(t1 - t0, 4),"s")

#Recordando si tengo una matriz
# C= A*B entonces tomará la siguiente forma:
# C[0,0] = A[0,0]*B[0,0] + A[0,1]-B[1,0] + A[0,2]*B[2,0]

#creamos la matriz en CPU
tam = 5000
A_cpu = torch.rand(tam,tam)
B_cpu = torch.rand(tam,tam)

t0 = time.perf_counter()
c_cpu = torch.mm(A_cpu, B_cpu)
t1 = time.perf_counter()
time_cpu = t1 - t0
print(f"Multiplicación en CPU: {round(time_cpu, 4)} s")

#GPU
if torch.cuda.is_available():
  A_gpu = A_cpu.to("cuda")
  B_gpu = B_cpu.to("cuda")

  _ = torch.mm(A_gpu, B_gpu)
  torch.cuda.synchronize()

  t0 = time.perf_counter()
  C_gpu = torch.mm(A_gpu, B_gpu)
  torch.cuda.synchronize()
  t1 = time.perf_counter()

  time_gpu = t1 - t0
  print(f"Multiplicación en GPU: {round(time_gpu, 4)} s")

A = torch.tensor([[1.,2.,3.],
               [3., 5.,6.],
               [7.,8.,9.]])

B = torch.tensor([[10.,11.,12.],
               [13.,14.,15.],
               [16.,17.,18.]])

C_cpu = A @ B
print("C_cpu = A @ B:", C_cpu)

if torch.cuda.is_available():
  A_gpu = A.to("cuda")
  B_gpu = B.to("cuda")
  C_gpu = A_gpu @ B_gpu
  C_back = C_gpu.cpu()

  print("C_gpu (regresada a CPU)", C_back)
  print("¿CPU == GPU?", torch.allclose(C_cpu, C_back))

#Trabajaremos con una matriz de 10x10
import torch

torch.manual_seed(7) #Semilla para que los experimentos sean reproducibles
#es decir, al usar la misma semilla, la  los numeros quedaran en el mismo orden

A = torch.rand(1000,1000)
B = torch.rand(1000,1000)

C_cpu = A @ B
print("C_cpu[0,0] =", float(C_cpu[0,0]))

if torch.cuda.is_available():
  A_gpu = A.to("cuda")
  B_gpu = B.to("cuda")
  C_gpu = A_gpu @ B_gpu
  C_back = C_gpu.cpu()

  max_error = float((C_back - C_cpu).abs().max())
  print("max_error", max_error)

  #el max error es el valor entre uno y otro pero es muy chico pero hay diferencia

#Trabajar matrices de tamaño
# 1000x1000
# 5000x5000
# 10000x10000
# 50000x50000

#Red neuronal en GPU vs CPU

import time
import numpy as np
from tensorflow.keras import Sequential
from tensorflow.keras.layers import  Conv2D, MaxPooling2D, Flatten, Dense, Dropout
import matplotlib.pyplot as plt
import tensorflow as tf

class TimeHistory(tf.keras.callbacks.Callback):
  def on_train_begin(self, logs=None):
    self.times = []
  def on_epoch_begin(self, epoch, logs=None):
    self.t0 = time.perf_counter()
  def on_epoch_end(self, epoch, logs=None):
      dt = time.perf_counter() - self.t0
      self.times.append(dt)
      print(f"[tiempo] Epoca{epoch+1}: {dt:.3f}, s")

time_cb = TimeHistory()

(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()

X_train = X_train.astype("float32") / 255.0
X_test = X_test.astype("float32") / 255.0

X_train = X_train[..., np.newaxis]
X_test = X_test[..., np.newaxis]

model = Sequential([
    Conv2D(32, (3,3), activation="relu", input_shape = (28,28,1)),
    MaxPooling2D((2,2)),
    Conv2D(64, (3,3), activation="relu"),
    MaxPooling2D((2,2)),
    Flatten(),
    Dense(64, activation="relu"),
    Dense(10, activation="softmax")])

model.compile(
    loss="sparse_categorical_crossentropy",
    optimizer= tf.keras.optimizers.Adam(learning_rate=0.001),
    metrics=["accuracy"]
)

t0_total = time.perf_counter()
history = model.fit(
    X_train, y_train,
    epochs = 10,
    batch_size = 64,
    validation_split=0.2,
    verbose =1,
    callbacks=[time_cb]
)
t1_total = time.perf_counter()

print("tiempos por epoca:", [round(t,3) for t in time_cb.times])
print("promedio / epoca:", round(sum(time_cb.times)/len(time_cb.times),3), "s")
print("Tiempo total:" , round(t1_total - t0_total,3), "s")

test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
print("Test loss:", round(float(test_loss), 4))
print("Test accuracy:", round(float(test_acc), 4))

plt.figure()
plt.plot(history.history["loss"], label="loss")
plt.plot(history.history["val_loss"], label="val_loss")
plt.xlabel("epocas")
plt.ylabel("loss")
plt.grid(True)
plt.legend()
plt.show()

plt.figure()
plt.plot(history.history["accuracy"], label="accuracy")
plt.plot(history.history["val_accuracy"], label="val_accuracy")
plt.xlabel("epocas")
plt.ylabel("accuracy")
plt.grid(True)
plt.legend()
plt.show()

import os
# Forzamos a TensorFlow a usar solo la CPU ocultando las GPUs
os.environ["CUDA_VISIBLE_DEVICES"] = "-1" # Es el interruptor maestro, le dice a TensorFlow que no existe ninguna tarjeta grafica GPU disponible -1

import time
import numpy as np
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
import matplotlib.pyplot as plt
import tensorflow as tf

# Verificación opcional para confirmar que estamos en CPU
print("Dispositivos disponibles:", tf.config.list_physical_devices())

class TimeHistory(tf.keras.callbacks.Callback):#Begin y end registran el tiempo que tarda en procesar los datos (antes y depues)
    def on_train_begin(self, logs=None):
        self.times = []
    def on_epoch_begin(self, epoch, logs=None):
        self.t0 = time.perf_counter()
    def on_epoch_end(self, epoch, logs=None):
        dt = time.perf_counter() - self.t0
        self.times.append(dt)
        print(f"[tiempo] Época {epoch+1}: {dt:.3f} s")

time_cb = TimeHistory()

# Carga de datos
# El datamnist contiene 60 000 imagenes de numeros del 0 al 9
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()

# Normalización
X_train = X_train.astype("float32") / 255.0 # Normalizamos los pixeles al dividirlos los dejamos en un rango del 0 al 1 lo que permite que lo calculos matematicos sean mas rapidos
X_test = X_test.astype("float32") / 255.0

# Añadir dimensión de canal (MNIST es escala de grises)
X_train = X_train[..., np.newaxis]
X_test = X_test[..., np.newaxis]

# Definición del modelo
model = Sequential([
    Conv2D(32, (3,3), activation="relu", input_shape=(28,28,1)), #Tensorflow espera una cuarta dimesión, ya que las imagenes son de 28x28
    MaxPooling2D((2,2)),
    Conv2D(64, (3,3), activation="relu"),#Son filtros que buscan patrone (lineas, curvas)
    MaxPooling2D((2,2)),# Reduce el tamaño de la imagen, quedandose solo con lo mas importante
    Flatten(),
    Dense(64, activation="relu"),
    Dense(10, activation="softmax")
    #Decide si las imagenes corresponden a 3,8,5
])
# Aqui elegimos el optimizador
model.compile(
    loss="sparse_categorical_crossentropy",#Funcion de perdida que mide que tan equivocado esta el modelo
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),# Adam es el mtor que ajusta los pesos
    metrics=["accuracy"]
)

# Entrenamiento
print("Iniciando entrenamiento en CPU...")
t0_total = time.perf_counter()
history = model.fit( # Es el proceso de aprendizaje
    X_train, y_train,
    epochs=10,
    batch_size=64,
    validation_split=0.2,
    verbose=1,
    callbacks=[time_cb]
)
t1_total = time.perf_counter()

# Resultados de tiempo
print("\n--- Resultados de Rendimiento en CPU ---")
print("Tiempos por época:", [round(t,3) for t in time_cb.times])
print("Promedio por época:", round(sum(time_cb.times)/len(time_cb.times),3), "s")
print("Tiempo total:", round(t1_total - t0_total,3), "s")

# Evaluación
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
print(f"Test accuracy: {round(float(test_acc), 4)}")

# Gráficas

# Genera graficas de perdida (Queremos que baje)
# y presicion (Queremos que suba)
plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(history.history["loss"], label="Train Loss")
plt.plot(history.history["val_loss"], label="Val Loss")
plt.title("Pérdida (Loss)")
plt.xlabel("Épocas")
plt.legend()
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(history.history["accuracy"], label="Train Acc")
plt.plot(history.history["val_accuracy"], label="Val Acc")
plt.title("Precisión (Accuracy)")
plt.xlabel("Épocas")
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()